### ISSUE TITLE
Build instructions for Ubuntu?

### ISSUE THREAD

**Issue by tsdye** [Chronomodel/chronomodel#103]
readme.txt gives instructions for Mac and Windows, but not Ubuntu.

**Comment by chrono35** [comment]
Hello Tom,
The reame.txt is an old file without update. 

We are finishing to develop a new version 2.0 by end of June, however it is still buggy on Linux...
____________________________

# If you need a ChronoModel version on Ubuntu
**This version is for a 32 bit system.**
You can find the last release at this adress:
 [https://github.com/Chronomodel/chronomodel/releases/download/v1.5.0/Chronomodel_v1.5.0_Ubuntu_i386.deb](https://github.com/Chronomodel/chronomodel/releases/download/v1.5.0/Chronomodel_v1.5.0_Ubuntu_i386.deb 
)

 If you want to install it, move to your download directory
 and type on a terminal:
 
` sudo dpkg -i Chronomodel_v1.5.0_Ubuntu_i386.deb`
 
 Then you can find ChronoModel with the other application.
 ____________________________
 
# If you want to compile it yourself
## You need to install, Qt5, QtCreator, Git and two special libraries:

`sudo apt-get update`

### Install Qt5
`sudo apt-get install qtdeclarative5-dev`
`sudo apt-get install qtbase5-dev`

### Install QtCreator
`sudo apt-get install qt-sdk`

### Install Git
`sudo apt-get install git-gui`
`sudo apt-get install gitk`

### Install libraries for Chronomodel
`sudo apt-get install fftw3*`
`sudo apt-get install libqt5svg5* `

## Make the compilation

`reset`
`cd ./Chronomodel`

## Download the code on GitHub
`git clone https://github.com/Chronomodel/chronomodel.git`

## Move inside the new directory
`cd chronomodel`

## Change the mode of all files, don't forget the last character "."
`sudo chmod -R a+rwx .`

## Cleaning previous release
`sudo rm -r build/release`


## Update linguistic file
`/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate Chronomodel.pro`
`/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease Chronomodel.pro`

## Compilation
`/usr/lib/x86_64-linux-gnu/qt5/bin/qmake Chronomodel.pro`
`make`

## Copy the directory Calib
`sudo cp -fra deploy/Calib build/release/Calib`

## Launch ChronoModel
`./build/release/Chronomodel`

**Comment by tsdye** [comment]
dk@pop-os:~/Downloads$ sudo dpkg -i Chronomodel_v1.5.0_Ubuntu_i386.deb 
dpkg-deb: error: 'Chronomodel_v1.5.0_Ubuntu_i386.deb' is not a Debian format archive
dpkg: error processing archive Chronomodel_v1.5.0_Ubuntu_i386.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 Chronomodel_v1.5.0_Ubuntu_i386.deb

**Comment by chrono35** [comment]
Hi Tom,
Exactly what I saw yesterday. I am on the problem. I'm just preparing the package for version 2.

**Comment by tsdye** [comment]
OK, I'm happy to wait for version 2.  I can test on Linux and OS X, if you like.

**Comment by nfrerebeau** [comment]
I successfully built Chronomodel v2.0.13 on Ubuntu 18.04 LTS (64 bit system). Here is the procedure I followed (assuming that the installation is done at the root of the user's directory):

1. Install dependencies
  1.1. Qt5
```shell
sudo apt-get install qtdeclarative5-dev
sudo apt-get install qtbase5-dev
```
  1.2. QtCreator
```shell
sudo apt-get install qtcreator
```
  1.3. libraries for Chronomodel
```shell
sudo apt-get install fftw3*
sudo apt-get install libqt5svg5*
```

2. Download 2.0.13 release
```shell
wget -c https://github.com/Chronomodel/chronomodel/archive/v2.0.13.tar.gz -O - | tar -xz
cd ~/chronomodel-2.0.13
```

3. Change the mode of all files
```shell
sudo chmod -R a+rwx .
```

4. Update linguistic file
```shell
/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate Chronomodel.pro
/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease Chronomodel.pro
```

5. Compile
```shell
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake Chronomodel.pro
make
```

6. Copy the directory Calib
```shell
sudo cp -fra deploy/Calib build/release/Calib
```

7. Launch ChronoModel
```shell
./build/release/chronomodel
```
