### ISSUE TITLE
Download partly broken (2.0, 1.5)?

### ISSUE THREAD

**Issue by RLumSK** [Chronomodel/chronomodel#105]
I tried to dowload ChronoModel for Windows and macOS from https://chronomodel.com/download-chronomodel-software-mac-windows. 

While the download always failed for version 2.0, I was able to download the Windows version of ChronoModel 1.5. The browser reports: 

>  Downloads/0CCLvToi.dmg.part could not be saved, because the source file could not be
> read.

I tried the browsers Safarie and Firefox (each newest versions available) and different internet connections (university and home).

**Comment by chrono35** [comment]
Hi Sebastian,

I'm not in charge of the web site. But I make a new tag on GitHub for this version where you can find the files.
https://github.com/Chronomodel/chronomodel/tree/v2.0.18

**Comment by RLumSK** [comment]
Ok, thank you. My mistake, I did not realise that you ship the binaries also via GitHub.
