### ISSUE TITLE
resol_t pour courbes de calibration 

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#12]
Réserver le resol_t pour la définition des courbes de calibration (et stats associées)

**Comment by helori** [comment]
resol_t (= calib resolution) est utilisé pour la calibration et les cumulatives (= répartition). Ces 2 courbes sont calculées en même temps.
Pour la version 1.4, on conserve ce système.
Il faudra adapter le support de la cumulative à la zone contenant de l'information.
Le titre du dialogue d'édition de la résolution a été changé pour "Resolution of distribution of calibrated date".

**Comment by helori** [comment]
Voir la question #37
