### ISSUE TITLE
Remplacer le mot-clé "Typo Ref."

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#15]
Remplacer le mot-clé "Typo Ref." par TYPO
possibilité de rentrer uniquement "TL" ou bien "OSL"
être insensible à la casse

**Comment by marieannevibet** [comment]
"être insensible à la casse" = ???

**Comment by chrono35** [comment]
La sensibilité à la casse est essentielle en informatique selon que les différents langages employés font ou non une distinction entre capitales et bas de casse. https://fr.wikipedia.org/wiki/Casse_(typographie)

**Comment by helori** [comment]
Fixed : 8ad36b0318abaf88e8549330c99b024796b8f908
"Typo Ref." est remplacé par "Typo". Plus simple en effet.
"TL/OSL" est conservé : on ne peut pas donner les 2 possibilités "TL" ou "OSL" dans les CSV car chaque plugin est repéré par un identifiant unique. 

Les anciens projets utilisant "Typo Ref." sont automatiquement convertis à l'ouverture.
