### ISSUE TITLE
Wiggle-matching: delta gaussien ?

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#18]
Wiggle-matching: est-ce que le delta gaussien prend en compte l'épaisseur des cernes de l'échantillon daté par 14C ?
Quelles sont les conséquences sur les calculs ?
Mieux expliquer le wiggle-matching.

**Comment by chrono35** [comment]
Mais peut-on vraiment apporter une réponse à cette question ?

**Comment by marieannevibet** [comment]
Le wiggle matching peut être fixe, uniforme ou gaussien.
Détails écrits dans le paragraphe 2.1.4 "The wiggle matching case"
