### ISSUE TITLE
changement le format de date, mauvais retour dans la fenêtre "results"

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#3]
dans application settings: quand on change le format de date, retour dans la fenêtre "results" sur un autre onglet

**Comment by chrono35** [comment]
C'est un mauvais comportement, mais pas un bug qui bloque ou une erreur de calcul.

**Comment by marieannevibet** [comment]
Est-ce que le bug est toujours visible avec la nouvelle version ?
