### ISSUE TITLE
Toujours accepter une mesure Mi +- si 

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#37]
Toujours accepter une mesure Mi +-Si même si la mesure est hors valeurs de la courbe de calibration sur la période d'étude.

**Comment by helori** [comment]
Les sujets #12 et celui-ci sont liés : Si on autorise des Mi +- si qui ne rencontrent pas la courbe de référence (et qui ont donc une densité calibrée nulle sur la plage d'étude), alors il faut que le marcheur aille chercher des valeurs sur R (en dehors de la plage d'étude) et que la fonction de répartition soit définie là où se trouve l'information (possiblement en dehors de la plage d'étude). Le "step" de calibration étant utilisé pour la fonction de répartition, les 2 questions sont donc liées!

Actuellement ce qui est fait n'est pas faux : le marcheur travaille bien sur R, et le calcul est empêché si des données calibrées sont hors plage d'étude. Il faudra lever cette barrière quand le nouveau système sera en place.

**Comment by marieannevibet** [comment]
Dans le cas où la densité calibrée est nulle sur la période d'étude, il faut changer de méthode MCMC d'échantillonnage et choisir un marcheur aléatoire (sur R). Le critère de Metropolis Hastings peut etre calculé car la courbe de référence est prolongée sur R. Et de nouveaux candidats peuvent aisément être proposés. 
En fait, on ne se sert pas de la fonction de répartition pour proposer un nouveau candidat dans ce cas là. 
Du coup, on ne devrait pas bloquer les cas où les densités calibrées sont nulles sur la plage d'étude.

**Comment by philippe-lanos** [comment]
Bonjour,

C'est bien noté.
Il faut effectivement programmer ce qui est décrit ci-dessous, mais je 
fais remarquer qu'il manque un cas de figure qu'il faut aussi traiter.
Ce vient du fait que plage d'étude sur theta et plage de calibration sur 
ti peuvent se chevaucher selon différentes configurations.
Ceci entraîne par ailleurs des précautions à prendre au niveau de 
l'affichage des densités calibrées des data.
Je vais vous envoyer les scans de mes notes que je mets à jour suite à 
la réunion avec PhD et Helori vendredi 27/11.

Un gros travail d'amélioration et de debug a été réalisé par PhD et Helori.
Il reste encore une semaine avec Helori pour régler la question des ti 
et, si possible, la question de la sélection/mémoire des results.

Très bon WE
Phil

Le 27/11/2015 16:20, marieannevibet a écrit :

> Dans le cas où la densité calibrée est nulle sur la période d'étude, 
> il faut changer de méthode MCMC d'échantillonnage et choisir un 
> marcheur aléatoire (sur R). Le critère de Metropolis Hastings peut 
> etre calculé car la courbe de référence est prolongée sur R. Et de 
> nouveaux candidats peuvent aisément être proposés.
> En fait, on ne se sert pas de la fonction de répartition pour proposer 
> un nouveau candidat dans ce cas là.
> Du coup, on ne devrait pas bloquer les cas où les densités calibrées 
> sont nulles sur la plage d'étude.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Chronomodel/chronomodel/issues/37#issuecomment-160158715.
> 
> ## 
> 
> ---

---

_Philippe LANOS  -  Directeur de Recherche CNRS  -_

Institut de Recherche sur les Archéomatériaux (IRAMAT) - CNRS UMR 5060

Centre de Recherche en Physique Appliquée à l'Archéologie (CRPAA)

Université Bordeaux 3

_/Lieu de travail:
/_Université de Rennes 1 "Géosciences-Rennes", Bât. 15, Equipe 
"Paléo-Archéomagnétisme"

Campus scientifique de Beaulieu, CS 74205, 35042 RENNES Cedex

_philippe.lanos@univ-rennes1.fr 
mailto:philippe.lanos@univ-rennes1.fr__Tel. : +33 (0)2 23 23 56 
39          mobile: 06 89 59 39 49_

---

**Comment by chrono35** [comment]
La densité calibrée ne peut avoir une valeur nulle que lorsque la vraisemblance retourne une valeur nulle sur tout l'intervalle. Ceci est du à un problème d'évaluation par la fonction exp() . Si la densité calibrée est nulle partout une alerte est mise dans la miniature de de la data "not computable".
Si la courbe de répartition est vide, on considère qu’il n’y a pas d’erreur de mesure, ni de courbe de calibration, ni de plugin. Par hypothèse, la valeur existe en dehors de la courbe de référence utilisée.
- Donc on initialise ti en dehors de cette courbe. Pour cela, on tire par boxMuller une valeur dans une gaussienne centrée et de variance égale à la largeur de la plage d’étude (tmax-tmin). Si cette valeur est négative, on l’ajoute à tmin, si la valeur est positive on l’ajoute à tmax.
- Si l’échantillonneur est défini avec la méthode par inversion, on le change et on force l’utilisation de la méthode MH Symétrique.

![capture d ecran 2016-03-08 a 14 35 56](https://cloud.githubusercontent.com/assets/10709644/13603110/26f201e2-e53b-11e5-8f43-ad44bec9e148.png)
