### ISSUE TITLE
Créer le fichier *.chr.dat 

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#4]
Le fichier *.chr.dat doit contenir les densités calibrées et les chaines MCMC (traces) : ceci évite de refaire les calculs et nous amène directement à la fin du RUN.
Prévoir le cas où impossibilité d'ouvrir avec le .dat: mettre une alerte pour dire de refaire les calculs MCMC.
Mettre la version du logiciel pour détecter si le .DAT est compatible

**Comment by philippe-lanos** [comment]
Pb de temps de chargement des densités calibrées : une barre de progression a été ajoutée pendant le temps de chargement du CHR

**Comment by chrono35** [comment]
Fait sur dernière version, exportation possible par courbe
