### ISSUE TITLE
Pb initialisation des theta avec contraintes Strati

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#43]
Optimiser la fonction modelutilities ::unsortEvents (pour l’initialisation des faits) : faire un swap aléatoire par exemple.
Utiliser la fonction dans STL:algorithme

**Comment by philippe-lanos** [comment]
Pb repéré sur init des theta quand contraintes strati
Erreur d’initialisation avec l’exemple d’Avellino : gros modèle avec multiples contraintes sur events et phases, qui plante CM. Revoir l’algo d’init…

**Comment by chrono35** [comment]
Fait sur dernière version
