### ISSUE TITLE
Afficher les intervalles de phase

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#48]
Afficher les "intervalles de phase" au-dessus des intervalles de crédibilité de début et de fin de phase, selon les calculs mis au point par Anne (mars 2015).
Terminologie français/anglais proposée: 
"intervalle de phase" = "phase interval" : l'expression "intervalle de recouvrement" n'est pas appropriée pour les archéologues.
"intervalle d'écart" (entre deux phases) = "intervening period" (proposé par William Banks le 17/11/15)

**Comment by philippe-lanos** [comment]
La terminologie a changé en fonction de l'article "Phase"
Calcul des intervalles de « Phase time range », de « Gap range » et de « Transition range » 
Les résultats sont dans le LOG

**Comment by chrono35** [comment]
Fait sur dernière version
