### ISSUE TITLE
Proportion de valeurs de ti hors plage

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#49]
Dans résultat Stat sur les ti: indiquer proportion de valeurs de ti hors plage d'étude si différente de 0%
ou bien : afficher le pourcentage de région HPD hors période d'étude
- Info sur ti min et ti max

**Comment by philippe-lanos** [comment]
Sur le graphe:
Mettre une alerte lorsque les Crédibilités possèdent des limites en dehors de la plage d’étude.
Corrigé : Alerte mise dans le LOG
Reste à faire : message d’alerte sur le graphique des densités pour dire que crédibilité est hors plage d’étude.

**Comment by chrono35** [comment]
Fait sur dernière version, ajout de flèches à droite et à gauche
