### ISSUE TITLE
Affichage créneau d'une borne invisible en dessous de 2

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#53]
Affichage créneau d'une borne invisible en dessous de 2

**Comment by chrono35** [comment]
Je propose de mettre une ou deux barres verticales pour indiquer la position des bornes.
SHA e592acf23b77634e9675a31e967e6b9fa4f99ab7

![capture d ecran 2015-11-16 a 18 31 38](https://cloud.githubusercontent.com/assets/10709644/11276217/758aac4c-8ee1-11e5-89f0-b15655aa4035.png)

Sur Bound : Bound 1 en bleu, une borne définie entre deux valeurs, la première barre représente le début de l'intervalle et la deuxième la fin.

Sur Bound : untitleedé en rouge, une borne fixe à une valeur, la barre rouge visualise cette valeur sur l'axe.

**Comment by philippe-lanos** [comment]
![Uploading Capture d’écran 2015-11-16 à 18.31.38.png…]()

**Comment by helori** [comment]
Dans la scène, côté modélisation, les bornes uniformes sont représentées "comme un créneau" et les bornes fixes sont présentées comme une barre verticale.

Dans les résultats, en transparence de la distribution a posteriori, les bornes sont représentées par des barres verticales comme suggéré par Ph.D. (bornes uniformes : une barre pour le début et une pour la fin).

Les problèmes d'affichage sont réglés (affichage en dehors des axes impossible à présent, et affichage correct quelque soit le zoom).
