### ISSUE TITLE
Refaire panneau de sélection des densités à afficher

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#58]
Permettre l’affichage des graphes à partir d’un panneau de sélection : choix des phases, Events, Dates avec Densités calibrées. Les zones « nothing to display » ne doivent pas apparaître.

**Comment by chrono35** [comment]
C'est l'ajout principale de la Version 2.0.0

**Comment by philippe-lanos** [comment]
Par la même occasion, l’ordre des graphes pourrait être contrôlé.
soit manuellement,
soit automatiquement par exemple du plus ancien au plus récent

**Comment by philippe-lanos** [comment]
Zoom sur durée de phase
Pb échelle des densités a posteriori des individual std deviations
Le zoom ne permet pas de voir convenablement les densités : normalement si…
Difficulté de mise à zéro : possibilité d’un réglage en utilisant le zoom sur x et les boites
Changer l’échelle de durée commune en bas des Results : impossible pour le moment
Tout ceci est à revoir avec la refonte de la partie Results.

**Comment by chrono35** [comment]
Fait sur dernière version
