### ISSUE TITLE
Création fichier ref personnel

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#6]
Expliquer dans manuel comment fabriquer et importer un fichier de référence personnel.

**Comment by marieannevibet** [comment]
S'agit-il des courbes de référence associées aux différents types de datation ?

**Comment by chrono35** [comment]
Dans un premier temps, juste les courbes utilisables par le plugin Gauss (sous entendu: mesure gaussienne). Car effectivement, les fichiers 14C et ref (utilisés par AM) suivent une convention connue dans chacune des disciplines corrspondantes.

**Comment by marieannevibet** [comment]
Il est possible d'importer facilement des courbes de réference pour les data Gauss, AM et C14. 
Voir le détail dans la section 3.2.4 "Including measurements" du Guide de l'utilisateur
