### ISSUE TITLE
Crash quand "alt" sur un event

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#63]

**Comment by chrono35** [comment]
Problème à mieux cerner! Je n'arrive pas à produire de crash.

**Comment by helori** [comment]
Très rare, présent depuis la première version de l'application mais personne ne l'a remontré...
Détecté en phase de développement mais aucun process n'a permis de le reproduire.
Est-il toujours présent??

**Comment by philippe-lanos** [comment]
On clôt cet issue car BUG reproduit depuis.
