### ISSUE TITLE
Sous windows, absence de fichier Uninstall

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#64]

**Comment by helori** [comment]
Il y a un fichier uninstall dans le dossier "ChonoModel" (dans Program Files).
Le gestionnaire de programmes de Windows permet aussi de désinstaller proprement.

Il serait possible de modifier le fichier InnoSetup pour ajouter le uninstall au menu Quick Launch.
Est-ce vraiment utile?

**Comment by marieannevibet** [comment]
Avec les versions précédentes de ChronoModel, notamment 1.1, il était possible de désinstaller rapidement le logiciel. C'est dommage que cette fonction ne soit plus accessible.
