### ISSUE TITLE
Affichage courbe de calibration pour une mesure Gauss none

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#68]
Affichage de data Gauss dans un fait (onglet Properties) : (No calibration) quand "None" is selected. Pourtant, en cliquant sur "Calibrate", on obtient un "Calibration process" ainsi qu'une "Distribution of calibrated date", ce qui n'est pas cohérent.

> Revoir le texte associé au choix de calibration

**Comment by chrono35** [comment]
Effectivement c'est incohérent. C'est corrigé.
SHA f4554c735bbbd3edec8d68e0bd297649a90b73b5
