### ISSUE TITLE
Calibrate - Affichage

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#69]
Il y a un souci d'actualisation de l'affichage de la fenêtre "Calibrate" correspondant à une ref typo. 
Quand on visualise le résultat de calibration individuelle d'un autre type de mesure, des résultats stat apparaissent en bas de la fenêtre. Ces résultats ne disparaissent pas quand ensuite on demande l'affichage de cette même fenêtre pour une ref typo.

**Comment by chrono35** [comment]
Aujourd'hui le problème est corrigé sur la branche experimental. Il a suffit d'effacer la boite texte avant affichage des résultats.

**Comment by helori** [comment]
Corrigé depuis le merge avec la branche experimentale.
