### ISSUE TITLE
Supprimer la détection de date invalide au moment du RUN

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#71]
Le bouton RUN ne doit pas être désactivé par la présence de dates invalides.
Une boite de dialogue permettant de retrouver les dates invalides (et aussi leur Event) doit s'afficher au RUN avant même la validation du modèle.

**Comment by helori** [comment]
Fixed : 871f95ef165af39d7a5ae7ac12d72edfe6170d1c
