### ISSUE TITLE
Choix de la méthode MCMC pour les ti quand Mi ne coupe pas la courbe de calibration

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#72]
Dans le cas de Mi qui ne coupent pas la courbe de calibration dans la plage d’étude, il faut utiliser une marche aléatoire pour les ti. Dans le rapport de Metropolis Hastings, il n’est pas question de la densité individuelle calibrée mais bien de la courbe de calibration prolongée sur R. Du coup, il n’y a pas de problème d’évaluation et normalement, les ti échantillonnés ainsi seront aussi principalement hors période d’étude. 
Question posée vendredi : pourquoi ne pas utiliser la période de calibration entière pour échantillonner les ti ? 
Réponse : si la zone de calibration est grande, on risque d’avoir affaire à des lois non intégrables et la convergence peut être difficile à obtenir. En plus s’il s’agit de l’AM, les courbes de calibrations sont périodiques, l’intégration de la courbe sur la zone de calibration entière risque de poser problème.

**Comment by helori** [comment]
Sujet redondant avec #37
