### ISSUE TITLE
Densités a posteriori - transparence des régions HPD

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#74]
Dans les versions antérieures de ChronoModel (version 1.1 par exemple), si la courbe de densité était dessinée en bleu, alors la région HPD associée était colorée en bleu légèrement transparent. Ce n'est plus le cas au-moins depuis la version 1.3.3 et c'est dommage.

**Comment by helori** [comment]
Corrigé au commit 2fd7ea3b5924d3e151cbdb5a4339c63bcf36f5ad
