### ISSUE TITLE
Plugin GAUSS - Export / Import fichier CSV et processus de calibration

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#75]
Quand on ajoute une mesure de Gauss et qu'on choisit "no calibration process" ou "Use costum curve file", le fichier CSV associé à l'export de toutes les data du projet ne contient pas ces infos. Si bien que lorsqu'on importe ce fichier précédemment exporter, les infos sont manquantes. 
Le choix du processus de calibration des data gaussiennes ne peut se faire qu'à la main dans la version 1.3.4.

**Comment by marieannevibet** [comment]
Ce commentaire est une redite du commentaire #14

**Comment by helori** [comment]
Corrigé : 80621b6e7f6d3e2b257048336de9aa6b5796a5b7
Le format CSV requis contient un nombre de colonne qui dépend du type choisi (none, curve, equation).
Exemple : 

> Gauss;Gauss Curve;100;50;example_csv_ref.csv
> Gauss;Gauss None;0;50;none
> Gauss;Gauss equation;0;50;equation;0;1;0

La première ligne contient : Gauss / Nom Date / Mesure / Erreur / courbe (fichier)
La seconde contient : Gauss / Nom Date / Mesure / Erreur / "none" (ou "")
La troisième contient : Gauss / Nom Date / Mesure / Erreur / "equation" / a / b / c

Les termes "none" et "equation" sont des mots clés.
