### ISSUE TITLE
Bound: mauvais contrôle des bornes à la saisie

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#78]
Empêcher de rentrer des valeurs de borne inversées

**Comment by chrono35** [comment]
Aujourd'hui sur la branche experimental. Il n'y a pas de boite d'alerte, mais la "calibration" n'apparait pas et dans la miniature, il est écrit 'Invalid Bound". Dans ce cas la miniature ne disparait pas lors le zoom est petit. L'exemple ci-dessous montre une borne fixe avec une valeur supérieure à la plage d'étude.
![capture d ecran 2015-12-04 a 16 20 43](https://cloud.githubusercontent.com/assets/10709644/11593162/05c877fe-9aa3-11e5-86ea-c575ca29b175.png)
