### ISSUE TITLE
Bound: contrôle de la miniature en fonction du zoom

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#79]
faire disparaître le rectangle blanc en même temps que les dates des Events

**Comment by chrono35** [comment]
![capture d ecran 2015-12-04 a 11 51 14](https://cloud.githubusercontent.com/assets/10709644/11628012/1fd27264-9cef-11e5-94dd-0edd3330685e.png)
Aujourd'hui fait sur la branche experiemental

**Comment by chrono35** [comment]
Régler lors de la fusion des branches
