### ISSUE TITLE
Mettre une alerte quand un modèle nécessite une courbe de référence manquante.

### ISSUE THREAD

**Issue by chrono35** [Chronomodel/chronomodel#81]
Si on charge un modèle nécessitant une courbe de référence absente dans les répertoires. Il faut avertir l'utilisateur et avoir la possibilité d'ouvrir quand même le modèle.

**Comment by chrono35** [comment]
Aujourd'hui c'est fait sur la branche experimental.
Alerte au chargement et message dans la description.

![capture d ecran 2015-12-04 a 11 52 37](https://cloud.githubusercontent.com/assets/10709644/11587981/96837ddc-9a7d-11e5-9454-b33b5891f48f.png)

![capture d ecran 2015-12-04 a 11 53 42](https://cloud.githubusercontent.com/assets/10709644/11588000/bb1f706a-9a7d-11e5-834a-ae0000f34d6a.png)

De même, si on charge une courbe non valide, elle apparait en rouge dans la liste des preferences du plugin et elle ne sera pas visible dans le choix a la saisie d'une data.

![capture d ecran 2015-12-04 a 16 45 16](https://cloud.githubusercontent.com/assets/10709644/11593819/ade6582c-9aa6-11e5-99a8-b6f39226e83a.png)

**Comment by helori** [comment]
Fixed. The dialog box is not shown anymore in case of large amount of dates
