### ISSUE TITLE
Affichage de l'échelle des abscisses

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#85]
On ne peut pas toujours bien lire le label des abscisses de fin de période d'étude, notamment sur le graphique de calibration. 
Exemple : sur une plage d'étude de -2 000 à -1 000, on obtient le graphique suivant : 
![capture d ecran 2016-03-01 a 16 31 30](https://cloud.githubusercontent.com/assets/15785508/13432743/2fcdd852-dfcf-11e5-9a8c-fb1dbe61c5c5.png)

On a l'impression que la plage d'étude est -2 000 à -100. C'est un souci.

**Comment by chrono35** [comment]
C'est corrigé dans mes commits locaux (sur mon disque dure)
![capture d ecran 2016-03-11 a 17 14 55](https://cloud.githubusercontent.com/assets/10709644/13708044/d6d316fa-e7ac-11e5-8bf8-f0d7983651b8.png)

**Comment by chrono35** [comment]
Fait sur dernière version
