### ISSUE TITLE
Version MAC OS et fixation des seeds de départ des MCMC

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#89]
La version Windows permet d'effectuer plusieurs fois le même calcul des MCMC avec un même seed de départ. On obtient bien des résultats identiques.
Avec la version MAC OS, ça ne fonctionne pas. Les résultats sont différents.
A revoir donc !

**Comment by philippe-lanos** [comment]
La chaîne aléatoire change pour une même graine entre le run 1 et le run 2, à partir du run 3 la suite des valeurs de chaines est identique : Pourquoi ?
