### ISSUE TITLE
Tips associés à l'import d'un fichier CSV

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#90]
Retirer la phrase "You can insert information in the table, you can use two keywords : ..." car pas assez claire. Il faudrait, éventuellement, détailler ce point dans le guide.

Par contre, il FAUT ajouter une ligne à propos des séparateurs CSV. 
"Be careful, cell separator and decimal separator of the CSV file should be those defined in the Application Settings, otherwise the CSV file will not be opened."

**Comment by chrono35** [comment]
Le message est changé
![capture d ecran 2016-03-08 a 14 05 44](https://cloud.githubusercontent.com/assets/10709644/13602469/2a761b04-e537-11e5-85ff-055172853904.png)
