### ISSUE TITLE
Cas des bounds et Cas des phases constituées d'une seule Bound

### ISSUE THREAD

**Issue by marieannevibet** [Chronomodel/chronomodel#92]
Il y a des soucis (cf capture d'écran suivante)

> region HPD et intervalle de crédibilité associé à une borne fixe !
> pas d'affichage de densité des début et fin de phase
> message : duration is not estimated => faux. La durée = 0 car debut = fin de phase
> affichage des statistiques de debut et fin de phase à revoir

![capture d ecran 2016-03-11 a 09 49 38](https://cloud.githubusercontent.com/assets/15785508/13702894/0e05ed52-e792-11e5-99c7-75469c8962b5.png)

**Comment by chrono35** [comment]
Fait sur dernière version
