### ISSUE TITLE
MCMC: pb contrôle dans settings MCMC

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#95]
MCMC settings
Contrôle des paramètres saisis dans la boîte MCMC Settings, les contrôles sont faits après la saisie et les éventuelles corrections sont visibles seulement à la réouverture (Pas de contrôle au chargement de fichier) -> contrôle à améliorer et à faire directement lors de la saisie.

**Comment by chrono35** [comment]
Fait sur dernière version
