### ISSUE TITLE
Affichage: Pb échelle Y sur graphes dans « results »

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#96]
Results sur history: l'échelle Y ne s'adapte pas en fonction de la zone zoomée. Gênant quand valeur initiale très grande et le reste des valeurs très confiné.
BUG : Pb échelle Y sur acceptation rate sur graphe Event avec MH random walk : l’échelle est celle sur les dates, et non sur [0, 100]. Pb de rafraichissement lors du clic sur onglets ou sur zoom.

**Comment by chrono35** [comment]
Fait sur dernière version
