### ISSUE TITLE
Event: suppression Event et Data

### ISSUE THREAD

**Issue by philippe-lanos** [Chronomodel/chronomodel#98]
Quand on efface un event, les data restent (et on peut encore calibrer)

**Comment by chrono35** [comment]
La gestion de la multi-selection entre les phases et les events est délicates. On peut avoir sélectionné des Events via le panneau Phases et en même temps via le panneau Events et alors on ne sait plus ce qu'on a vraiment sélectionné. Si dans ce cas on efface les Events, on peut effacer des Events sélectionnés via, le côté phases, sans le savoir.
![capture d ecran 2016-05-03 a 17 25 31](https://cloud.githubusercontent.com/assets/10709644/14988443/1b91d972-1154-11e6-8c4f-d4dff1358a41.png)

**Comment by chrono35** [comment]
Fait sur dernière version
